### YamlMime:ManagedReference
items:
- uid: FastEndpoints.ValidationFailureException
  commentId: T:FastEndpoints.ValidationFailureException
  id: ValidationFailureException
  parent: FastEndpoints
  children:
  - FastEndpoints.ValidationFailureException.#ctor
  - FastEndpoints.ValidationFailureException.#ctor(System.String)
  - FastEndpoints.ValidationFailureException.#ctor(System.String,System.Nullable{Exception})
  langs:
  - csharp
  - vb
  name: ValidationFailureException
  nameWithType: ValidationFailureException
  fullName: FastEndpoints.ValidationFailureException
  type: Class
  source:
    id: ValidationFailureException
    path: D:\SOURCE-CONTROL\FastEndpoints\Api-Reference\Source\src\Library\Exceptions.cs
    startLine: 5
  assemblies:
  - FastEndpoints
  namespace: FastEndpoints
  summary: "\nthe exception thrown when a validation error has occured. this class is only useful in unit tests.\n"
  example: []
  syntax:
    content: 'public class ValidationFailureException : Exception'
    content.vb: >-
      Public Class ValidationFailureException

          Inherits Exception
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: FastEndpoints.ValidationFailureException.#ctor
  commentId: M:FastEndpoints.ValidationFailureException.#ctor
  id: '#ctor'
  parent: FastEndpoints.ValidationFailureException
  langs:
  - csharp
  - vb
  name: ValidationFailureException()
  nameWithType: ValidationFailureException.ValidationFailureException()
  fullName: FastEndpoints.ValidationFailureException.ValidationFailureException()
  type: Constructor
  source:
    id: .ctor
    path: D:\SOURCE-CONTROL\FastEndpoints\Api-Reference\Source\src\Library\Exceptions.cs
    startLine: 7
  assemblies:
  - FastEndpoints
  namespace: FastEndpoints
  syntax:
    content: public ValidationFailureException()
    content.vb: Public Sub New
  overload: FastEndpoints.ValidationFailureException.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: FastEndpoints.ValidationFailureException.#ctor(System.String)
  commentId: M:FastEndpoints.ValidationFailureException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: FastEndpoints.ValidationFailureException
  langs:
  - csharp
  - vb
  name: ValidationFailureException(String)
  nameWithType: ValidationFailureException.ValidationFailureException(String)
  fullName: FastEndpoints.ValidationFailureException.ValidationFailureException(System.String)
  type: Constructor
  source:
    id: .ctor
    path: D:\SOURCE-CONTROL\FastEndpoints\Api-Reference\Source\src\Library\Exceptions.cs
    startLine: 9
  assemblies:
  - FastEndpoints
  namespace: FastEndpoints
  syntax:
    content: public ValidationFailureException(string message)
    parameters:
    - id: message
      type: System.String
    content.vb: Public Sub New(message As String)
  overload: FastEndpoints.ValidationFailureException.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: FastEndpoints.ValidationFailureException.#ctor(System.String,System.Nullable{Exception})
  commentId: M:FastEndpoints.ValidationFailureException.#ctor(System.String,System.Nullable{Exception})
  id: '#ctor(System.String,System.Nullable{Exception})'
  parent: FastEndpoints.ValidationFailureException
  langs:
  - csharp
  - vb
  name: ValidationFailureException(String, Nullable<Exception>)
  nameWithType: ValidationFailureException.ValidationFailureException(String, Nullable<Exception>)
  fullName: FastEndpoints.ValidationFailureException.ValidationFailureException(System.String, System.Nullable<Exception>)
  type: Constructor
  source:
    id: .ctor
    path: D:\SOURCE-CONTROL\FastEndpoints\Api-Reference\Source\src\Library\Exceptions.cs
    startLine: 11
  assemblies:
  - FastEndpoints
  namespace: FastEndpoints
  syntax:
    content: public ValidationFailureException(string message, Exception? innerException)
    parameters:
    - id: message
      type: System.String
    - id: innerException
      type: System.Nullable{Exception}
    content.vb: Public Sub New(message As String, innerException As Exception?)
  overload: FastEndpoints.ValidationFailureException.#ctor*
  nameWithType.vb: ValidationFailureException.ValidationFailureException(String, Nullable(Of Exception))
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: FastEndpoints.ValidationFailureException.ValidationFailureException(System.String, System.Nullable(Of Exception))
  name.vb: ValidationFailureException(String, Nullable(Of Exception))
references:
- uid: FastEndpoints
  commentId: N:FastEndpoints
  name: FastEndpoints
  nameWithType: FastEndpoints
  fullName: FastEndpoints
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: FastEndpoints.ValidationFailureException.#ctor*
  commentId: Overload:FastEndpoints.ValidationFailureException.#ctor
  name: ValidationFailureException
  nameWithType: ValidationFailureException.ValidationFailureException
  fullName: FastEndpoints.ValidationFailureException.ValidationFailureException
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Nullable{Exception}
  commentId: T:System.Nullable{Exception}
  parent: System
  definition: System.Nullable`1
  name: Nullable<Exception>
  nameWithType: Nullable<Exception>
  fullName: System.Nullable<Exception>
  nameWithType.vb: Nullable(Of Exception)
  fullName.vb: System.Nullable(Of Exception)
  name.vb: Nullable(Of Exception)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: Exception
    name: Exception
    nameWithType: Exception
    fullName: Exception
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: Exception
    name: Exception
    nameWithType: Exception
    fullName: Exception
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Nullable`1
  commentId: T:System.Nullable`1
  isExternal: true
  name: Nullable<T>
  nameWithType: Nullable<T>
  fullName: System.Nullable<T>
  nameWithType.vb: Nullable(Of T)
  fullName.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
